language: node_js
node_js:
  - "6"
env:
  - BUILD_DIR="../w20-ghp"
script:
  - rm -rf $BUILD_DIR
  - git clone https://$GITHUB_TOKEN@github.com/tomvit/w20.git $BUILD_DIR
  - cd $BUILD_DIR
  - git submodule update --init --recursive 
  - git checkout gh-pages
  - git pull origin/master --no-commit
  - git commit -m "merged with master on gh-pages build"
  - export COURSE_HOME=$(pwd)
  - echo $COURSE_HOME
  - $COURSE_HOME/humla/bin/create-toc.sh
  - $COURSE_HOME/humla/bin/generate-pdfs.sh
  - git add -A .
  - git commit -a -m "Travis #$TRAVIS_BUILD_NUMBER"
  - git push --quiet origin gh-pages > /dev/null 2>&1
