language: node_js
node_js:
  - "6"
env:
  - COURSE_HOME=$(pwd)
script:
  - echo $COURSE_HOME
  - $COURSE_HOME/humla/bin/create-toc.sh
  - $COURSE_HOME/humla/bin/generate-pdfs.sh
after_success: 
  - cd "$TRAVIS_BUILD_DIR"
  - git init
  - git checkout -b gh-pages
  - git add pdf
  - git add tos.json
  - git -c user.name='travis' -c user.email='travis' commit -m init
  - git push -f -q https://tomvit:$GITHUB_TOKEN@github.com/tomvit/w20 gh-pages
  - cd "$TRAVIS_BUILD_DIR"

#deploy:
#  provider: pages
#  skip_cleanup: true
#  github_token: $GITHUB_TOKEN 
#  on:
#    branch: master
