language: node_js
node_js:
  - "6"
env:
  - COURSE_HOME=$(pwd)
script:
  - git checkout gh-pages
  - git merge -m "merged with master on gh-pages build"
  - echo $COURSE_HOME
  - $COURSE_HOME/humla/bin/create-toc.sh
  - $COURSE_HOME/humla/bin/generate-pdfs.sh
after_success: 
  - cd "$TRAVIS_BUILD_DIR"
  - git branch
  - git add pdf
  - git add cache
  - git add toc.json
  - git -c user.name='travis' -c user.email='travis' commit -am "pdf and toc on new build"
  - git push -f -q https://tomvit:$GITHUB_TOKEN@github.com/tomvit/w20

