language: node_js
node_js:
  - "6"
env:
  - COURSE_HOME=$(pwd)
script:
  - $COURSE_HOME/humla/bin/create-toc.sh
  - $COURSE_HOME/humla/bin/generate-pdfs.sh
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN 
  target_branch: master
  on:
    branch: master
